spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    contentnegotiation:
      favor-parameter: true   # 开启请求参数内容协商（?format=json，显示为json|| ?format=xml 显示为xml）
  #  mvc:
#    static-path-pattern: /res/**

  resources:
    static-locations: [classpath:/haha/]
    add-mappings: true
    cache:
      period: 11000
server:
  servlet:
    context-path: /world

